name: Run Flask App

on:
  push:
    branches:
      - main

jobs:
  run-flask-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask requests RPi.GPIO werkzeug

    - name: Run Flask app
      run: |
        python app.py
